- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4865/workspace/ansible/target/MavenAnsibleWebApp2.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebApp2.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
