- name: Deploy to Tomcat
  hosts: web
  become: yes
  vars:
    war_file_path: "/default/path/if/none/specified"
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "{{ war_file_path }}"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebApp2.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted

